version: '3.8'

services:
  web:
    build: .
    ports:
      - "5006:5006"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/jinja_app
    depends_on:
      - db
    volumes:
      - .:/app
    command: python run.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=jinja_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: